### ISSUE TITLE
Curious 🧐 : what does the activity execution api do? 

### ISSUE THREAD

**Issue by longquanzheng** [northpowered/temporal-rest-executor#4]
Does it start or execute an activity? How does that work without a workflow? 

Also if so maybe better to call 

“activity/execute” 
“workflow/execute” as I believe post usually use a verb lol

**Comment by northpowered** [comment]
Execute

For separate remote activity it uses build-in workflow with `execute_activity`

Tnx for help with terms for non-native english speakers :)
